export type Artwork = {
  id: string;
  title: string;
  artist: string;
  date: string;
  image: string;
  alt: string;
  medium: string;
  dimensions: string;
  origin: string;
  classification: string;
  accent: string;
  mood: string;
  movement: string;
  era: string;
  paletteName: string;
  theme: string;
  editorial: string;
  license: string;
  sourceUrl: string;
};

const redirect = (file: string) =>
  'https://commons.wikimedia.org/wiki/Special:Redirect/file/' + encodeURIComponent(file) + '?width=1600';

const vanGogh = (
  seed: Omit<Artwork, 'artist' | 'medium' | 'classification' | 'movement' | 'license'>,
): Artwork => ({
  ...seed,
  artist: 'Vincent van Gogh',
  medium: 'Oil on canvas',
  classification: 'Painting',
  movement: 'Post-Impressionism',
  license: 'Public-domain artwork; digital-file provenance linked at source',
});

const publicDomainArtworks: Artwork[] = [
  vanGogh({
    id: 'starry-night',
    title: 'The Starry Night',
    date: 'June 1889',
    image: redirect('Vincent van Gogh Starry Night.jpg'),
    alt: 'The Starry Night by Vincent van Gogh, a swirling blue night sky over Saint-Rémy',
    dimensions: '73.7 × 92.1 cm',
    origin: 'Saint-Rémy-de-Provence',
    accent: '#244b8f',
    mood: 'Luminous',
    era: 'Saint-Rémy · 1889',
    paletteName: 'Cobalt Night',
    theme: 'Night',
    editorial: 'The sky does not sit above the landscape; it moves through it. Blue becomes atmosphere, rhythm and pressure at once.',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_Starry_Night.jpg',
  }),
  vanGogh({
    id: 'starry-rhone',
    title: 'Starry Night Over the Rhône',
    date: 'September 1888',
    image: redirect('Starry Night Over the Rhone.jpg'),
    alt: 'Starry Night Over the Rhône by Vincent van Gogh, blue river reflecting yellow stars and city lights',
    dimensions: '72.5 × 92 cm',
    origin: 'Arles',
    accent: '#1e4f86',
    mood: 'Tender',
    era: 'Arles · 1888',
    paletteName: 'River Blue',
    theme: 'Night',
    editorial: 'Artificial light and starlight share the same river. The painting turns reflection into a second sky.',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Starry_Night_Over_the_Rhone.jpg',
  }),
  vanGogh({
    id: 'sunflowers',
    title: 'Sunflowers',
    date: 'August 1888',
    image: redirect('Vincent van Gogh - Sunflowers (1888, National Gallery London).jpg'),
    alt: 'Sunflowers by Vincent van Gogh, a bouquet of yellow sunflowers in a yellow vase',
    dimensions: '92.1 × 73 cm',
    origin: 'Arles',
    accent: '#d8a928',
    mood: 'Ecstatic',
    era: 'Arles · 1888',
    paletteName: 'Chrome Yellow',
    theme: 'Sun',
    editorial: 'Yellow is not an accent here. It is the room, the air and the emotional temperature of the entire object.',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_Sunflowers_(1888,_National_Gallery_London).jpg',
  }),
  vanGogh({
    id: 'cafe-terrace',
    title: 'Café Terrace at Night',
    date: 'September 1888',
    image: redirect('Van Gogh - Terrasse des Cafés an der Place du Forum in Arles am Abend1FXD.jpg'),
    alt: 'Café Terrace at Night by Vincent van Gogh, a glowing yellow café under a deep blue starry sky',
    dimensions: '80.7 × 65.3 cm',
    origin: 'Arles',
    accent: '#e0a72b',
    mood: 'Luminous',
    era: 'Arles · 1888',
    paletteName: 'Gaslight Gold',
    theme: 'Night',
    editorial: 'Night becomes a color contrast rather than darkness. The warm terrace holds the street open like a stage.',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Van_Gogh_-_Terrasse_des_Caf%C3%A9s_an_der_Place_du_Forum_in_Arles_am_Abend1FXD.jpg',
  }),
  vanGogh({
    id: 'bedroom-arles',
    title: 'Bedroom in Arles',
    date: 'September 1889',
    image: redirect("Vincent van Gogh - Van Gogh's Bedroom in Arles - Google Art Project.jpg"),
    alt: 'Bedroom in Arles by Vincent van Gogh, a compact room with a wooden bed and strongly colored walls',
    dimensions: '57.5 × 74 cm',
    origin: 'Saint-Rémy version after Arles',
    accent: '#be6c38',
    mood: 'Quiet',
    era: 'Saint-Rémy · 1889',
    paletteName: 'Terracotta Rest',
    theme: 'Room',
    editorial: 'Perspective bends toward intimacy. The room is simple, but every plane of color insists on being felt.',
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_Van_Gogh%27s_Bedroom_in_Arles_-_Google_Art_Project.jpg",
  }),
  vanGogh({
    id: 'almond-blossom',
    title: 'Almond Blossom',
    date: 'February 1890',
    image: redirect('Vincent van Gogh - Almond Blossom - VGM F671.jpg'),
    alt: 'Almond Blossom by Vincent van Gogh, white flowering branches against a turquoise-blue sky',
    dimensions: '73.5 × 92 cm',
    origin: 'Saint-Rémy-de-Provence',
    accent: '#67a9b4',
    mood: 'Tender',
    era: 'Saint-Rémy · 1890',
    paletteName: 'Blossom Cyan',
    theme: 'Bloom',
    editorial: 'Branches enter the frame like calligraphy. The empty blue field makes growth feel both delicate and absolute.',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_Almond_Blossom_-_VGM_F671.jpg',
  }),
  vanGogh({
    id: 'wheatfield-crows',
    title: 'Wheatfield with Crows',
    date: 'July 1890',
    image: redirect('Van Gogh, Wheatfield with crows.jpg'),
    alt: 'Wheatfield with Crows by Vincent van Gogh, dark birds over a turbulent yellow field beneath a blue sky',
    dimensions: '50.5 × 103 cm',
    origin: 'Auvers-sur-Oise',
    accent: '#c7a42d',
    mood: 'Restless',
    era: 'Auvers · 1890',
    paletteName: 'Storm Wheat',
    theme: 'Field',
    editorial: 'Three paths press into a field that never resolves into destination. Sky, wheat and birds pull in different directions.',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Van_Gogh,_Wheatfield_with_crows.jpg',
  }),
  vanGogh({
    id: 'cypresses',
    title: 'Cypresses',
    date: 'June 1889',
    image: redirect('Vincent van Gogh Cypresses 1889.jpg'),
    alt: 'Cypresses by Vincent van Gogh, tall dark cypress trees rising against a turbulent sky',
    dimensions: '93.4 × 73 cm',
    origin: 'Saint-Rémy-de-Provence',
    accent: '#3e5d38',
    mood: 'Monumental',
    era: 'Saint-Rémy · 1889',
    paletteName: 'Cypress Green',
    theme: 'Earth',
    editorial: 'The trees are less background than architecture. Their dark vertical mass cuts through a landscape that refuses to stay still.',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_Cypresses_1889.jpg',
  }),
  vanGogh({
    id: 'self-portrait',
    title: 'Self-Portrait',
    date: '1889',
    image: redirect('Vincent van Gogh - Zelfportret, 1889 (National Gallery of Art).jpg'),
    alt: 'Self-Portrait by Vincent van Gogh, the artist facing the viewer against a swirling blue-green ground',
    dimensions: 'See source record',
    origin: 'Saint-Rémy-de-Provence',
    accent: '#4f7771',
    mood: 'Uncanny',
    era: 'Saint-Rémy · 1889',
    paletteName: 'Viridian Pulse',
    theme: 'Self',
    editorial: 'The face is held still while the field around it vibrates. Looking becomes reciprocal: the portrait appears to look back.',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_Zelfportret,_1889_(National_Gallery_of_Art).jpg',
  }),
  vanGogh({
    id: 'irises',
    title: 'Irises',
    date: 'May 1890',
    image: redirect('Vincent van Gogh - Irises (1890).jpg'),
    alt: 'Irises by Vincent van Gogh, violet-blue flowers set against a pale field',
    dimensions: '73.7 × 92.1 cm',
    origin: 'Saint-Rémy-de-Provence',
    accent: '#596db2',
    mood: 'Playful',
    era: 'Saint-Rémy · 1890',
    paletteName: 'Iris Violet',
    theme: 'Bloom',
    editorial: 'Color contrast makes every stem behave like a separate gesture. The bouquet becomes a field of small decisions.',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_Irises_(1890).jpg',
  }),
  vanGogh({
    id: 'first-steps',
    title: 'First Steps, after Millet',
    date: 'January 1890',
    image: redirect('First Steps, after Millet MET DP124808.jpg'),
    alt: 'First Steps, after Millet by Vincent van Gogh, parents reaching toward a small child in a garden',
    dimensions: '72.4 × 91.1 cm',
    origin: 'Saint-Rémy-de-Provence',
    accent: '#738665',
    mood: 'Tender',
    era: 'Saint-Rémy · 1890',
    paletteName: 'Garden Sage',
    theme: 'Family',
    editorial: 'Van Gogh called such copies translations. Here borrowed structure becomes personal through a completely rebuilt world of color.',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:First_Steps,_after_Millet_MET_DP124808.jpg',
  }),
  vanGogh({
    id: 'roses',
    title: 'Roses',
    date: '1890',
    image: redirect('Vincent van Gogh, Roses, 1890, NGA 72328.jpg'),
    alt: 'Roses by Vincent van Gogh, pale pink roses spread across a green-blue field',
    dimensions: 'See source record',
    origin: 'Saint-Rémy-de-Provence',
    accent: '#bca7a7',
    mood: 'Quiet',
    era: 'Saint-Rémy · 1890',
    paletteName: 'Faded Rose',
    theme: 'Bloom',
    editorial: 'The flowers are almost absorbed by the surrounding field. Softness becomes a study in how little contrast a painting needs to remain alive.',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh,_Roses,_1890,_NGA_72328.jpg',
  }),
  vanGogh({
    id: 'oleanders',
    title: 'Oleanders',
    date: 'August 1888',
    image: redirect('Vincent van Gogh - Oleander.jpg'),
    alt: 'Oleanders by Vincent van Gogh, pink and white flowers in a patterned jug beside a book',
    dimensions: '60.3 × 73.7 cm',
    origin: 'Arles',
    accent: '#c77979',
    mood: 'Ecstatic',
    era: 'Arles · 1888',
    paletteName: 'Oleander Coral',
    theme: 'Bloom',
    editorial: 'The still life feels active rather than arranged. Flowers push outward while the book anchors the composition in lived attention.',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_Oleander.jpg',
  }),
];

export async function fetchPublicDomainArtworks(signal?: AbortSignal): Promise<Artwork[]> {
  if (signal?.aborted) throw new DOMException('Aborted', 'AbortError');
  return publicDomainArtworks;
}
